variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - pages

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_TOKEN"    
  script:
    - docker build --pull -t matthewgall/whoisjs.com:latest .
    - docker push matthewgall/whoisjs.com:latest

pages:
  image: ubuntu:latest
  stage: pages
  script:
    - apt update && apt -y install wget
    - wget https://github.com/bukalapak/snowboard/releases/download/v2.0.3/snowboard-v2.0.3.linux-amd64.tar.gz
    - tar -zxvf snowboard-v2.0.3.linux-amd64.tar.gz
    - mkdir public/
    - cp favicon.ico public/
    - ./snowboard html -o public/index.html -q snowboard.apib
  artifacts:
      paths:
      - public
