services:
  - docker:dind

stages:
  - build
  - pages

pages:
  image: quay.io/bukalapak/snowboard:latest
  stage: build
  script:
    - mkdir public/
    - cp favicon.ico public/
    - snowboard html -o public/index.html -t docs/alpha.html -q snowboard.apib
  artifacts:
      paths:
      - public


build:
  image: docker:latest
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"